//Heman Baral
//CMSC 312

#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>

/* run locally on 'server' called by a remote client. */
static double sum_avg;

/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */


//change double to char

//change input data to char 

char * print_echo(char *input, CLIENT *client) 
  {


printf("%s\n",*input );

  //return( &sum_avg );
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */


//input_data to char
 
char * average_1_svc(char** input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( print_echo( input, client) );
  }
